### ISSUE TITLE
Possibility for integrating this with angular v6+

### ISSUE THREAD

**Issue by nalinmathur0** [KSubedi/transliteration-input-tools#1]
Hi, I came across your github page and saw this repository.
I am learning angular v6+ and want to use it as a package in angular.
Is it a possibility for you to make this an angular package and publish it on npm.

Thanks in Advance

**Comment by KSubedi** [comment]
It directly interfaces with the DOM so technically you should be able to use it with any framework. Angular integration is out of scope for this project as of now, but if anyone wants to drop a pull request I would be happy to consider merging it.
