### ISSUE TITLE
How can I use this in create-react-app

### ISSUE THREAD

**Issue by pratiksharm** [KSubedi/transliteration-input-tools#18]
I don't know webpack, But i followed your instructions on Client Side. To copy paste the  javascript bundle into the Public file of create react app. And then i tried to use it but didn't work.

Can you make a npm package//(or may be you already have but i can't find it). ?

Error i got

`Uncaught TypeError: Cannot read property 'addEventListener' of null
    at t.registerListeners (transliteration-input.bundle.js:1)
    at new t (transliteration-input.bundle.js:1)
    at new <anonymous> (transliteration-input.bundle.js:1)
    at r (transliteration-input.bundle.js:1)
    at (index):51`

**Comment by milantarami** [comment]
you are trying to add an event listener on null. make sure you are adding an event listener to DOM element

**Comment by Horopter** [comment]
@biomathcode Do you have a react demo I could use as a reference point? Preferably as a jsfiddle?

**Comment by biomathcode** [comment]
@Horopter I used https://github.com/burhanuday/react-transliterate instead. Hope it helps

**Comment by Horopter** [comment]
That's really cool. Thanks @biomathcode.
