### ISSUE TITLE
Including "transliteration-input-tools" in Rich text editors

### ISSUE THREAD

**Issue by AmalChandru** [KSubedi/transliteration-input-tools#28]
Is there any way to include these "transliteration-input-tools" within Rich Text editors like CKEditor or Quill? Have tried the regular call of `enableTransliteration( )` which seems not working. Adding the tried fix (in CKEditor ) and its console output. 

![code](https://user-images.githubusercontent.com/58633735/131071663-962b4b05-9ecc-49df-ac30-7c45587a7455.png)
![developertools](https://user-images.githubusercontent.com/58633735/131071667-94d75474-80a9-466d-ad16-1f8561915a6c.png)

**Comment by sumitgohil** [comment]
Same here. It does not work on Rich text Editor. Rich text editors seems to replace textarea with Content Editable Div. Please help if there is any workaround.
